[package]
name = "eister_os"
version = "0.1.0"
authors = ["Federico Pasqua <federico.pasqua.96@gmail.com>"]

[lib]
crate-type = ["staticlib"]

[dependencies]
rlibc = "1.0"
volatile = "0.1.0"
spin = "0.4.5"

